protos:
	protoc --proto_path=. --go_out=. --go_opt=module=github.com/chanmaoganda/fileshare/internal/proto --go-grpc_out=. --go-grpc_opt=module=github.com/chanmaoganda/fileshare/internal/proto fileshare.proto

@PHONY:clean
clean:
	rm 