// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: download.proto

package download

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_OK    Status = 0
	Status_ERROR Status = 1
	Status_RETRY Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "OK",
		1: "ERROR",
		2: "RETRY",
	}
	Status_value = map[string]int32{
		"OK":    0,
		"ERROR": 1,
		"RETRY": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_download_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_download_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{0}
}

type FileMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Sha256        string                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMeta) Reset() {
	*x = FileMeta{}
	mi := &file_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMeta) ProtoMessage() {}

func (x *FileMeta) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMeta.ProtoReflect.Descriptor instead.
func (*FileMeta) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{0}
}

func (x *FileMeta) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileMeta) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type DownloadTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *FileMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadTask) Reset() {
	*x = DownloadTask{}
	mi := &file_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadTask) ProtoMessage() {}

func (x *DownloadTask) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadTask.ProtoReflect.Descriptor instead.
func (*DownloadTask) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadTask) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

type DownloadSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *FileMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	ChunkNumber   int32                  `protobuf:"varint,2,opt,name=chunkNumber,proto3" json:"chunkNumber,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,3,opt,name=chunkSize,proto3" json:"chunkSize,omitempty"`
	ChunkList     []int32                `protobuf:"varint,4,rep,packed,name=chunkList,proto3" json:"chunkList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSummary) Reset() {
	*x = DownloadSummary{}
	mi := &file_download_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSummary) ProtoMessage() {}

func (x *DownloadSummary) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSummary.ProtoReflect.Descriptor instead.
func (*DownloadSummary) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{2}
}

func (x *DownloadSummary) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DownloadSummary) GetChunkNumber() int32 {
	if x != nil {
		return x.ChunkNumber
	}
	return 0
}

func (x *DownloadSummary) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *DownloadSummary) GetChunkList() []int32 {
	if x != nil {
		return x.ChunkList
	}
	return nil
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *FileMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Total         int32                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_download_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{3}
}

func (x *FileChunk) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *FileChunk) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FileChunk) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DownloadStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *FileMeta              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ChunkList     []int32                `protobuf:"varint,3,rep,packed,name=chunkList,proto3" json:"chunkList,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadStatus) Reset() {
	*x = DownloadStatus{}
	mi := &file_download_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadStatus) ProtoMessage() {}

func (x *DownloadStatus) ProtoReflect() protoreflect.Message {
	mi := &file_download_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadStatus.ProtoReflect.Descriptor instead.
func (*DownloadStatus) Descriptor() ([]byte, []int) {
	return file_download_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadStatus) GetMeta() *FileMeta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *DownloadStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DownloadStatus) GetChunkList() []int32 {
	if x != nil {
		return x.ChunkList
	}
	return nil
}

var File_download_proto protoreflect.FileDescriptor

const file_download_proto_rawDesc = "" +
	"\n" +
	"\x0edownload.proto\">\n" +
	"\bFileMeta\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"-\n" +
	"\fDownloadTask\x12\x1d\n" +
	"\x04meta\x18\x01 \x01(\v2\t.FileMetaR\x04meta\"\x8e\x01\n" +
	"\x0fDownloadSummary\x12\x1d\n" +
	"\x04meta\x18\x01 \x01(\v2\t.FileMetaR\x04meta\x12 \n" +
	"\vchunkNumber\x18\x02 \x01(\x05R\vchunkNumber\x12\x1c\n" +
	"\tchunkSize\x18\x03 \x01(\x03R\tchunkSize\x12\x1c\n" +
	"\tchunkList\x18\x04 \x03(\x05R\tchunkList\"j\n" +
	"\tFileChunk\x12\x1d\n" +
	"\x04meta\x18\x01 \x01(\v2\t.FileMetaR\x04meta\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x05R\x05total\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"e\n" +
	"\x0eDownloadStatus\x12\x1d\n" +
	"\x04meta\x18\x01 \x01(\v2\t.FileMetaR\x04meta\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x1c\n" +
	"\tchunkList\x18\x03 \x03(\x05R\tchunkList*&\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x00\x12\t\n" +
	"\x05ERROR\x10\x01\x12\t\n" +
	"\x05RETRY\x10\x022l\n" +
	"\x0fDownloadService\x12.\n" +
	"\vPreDownload\x12\r.DownloadTask\x1a\x10.DownloadSummary\x12)\n" +
	"\bDownload\x12\n" +
	".FileChunk\x1a\x0f.DownloadStatus(\x01B\fZ\n" +
	"./downloadb\x06proto3"

var (
	file_download_proto_rawDescOnce sync.Once
	file_download_proto_rawDescData []byte
)

func file_download_proto_rawDescGZIP() []byte {
	file_download_proto_rawDescOnce.Do(func() {
		file_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_download_proto_rawDesc), len(file_download_proto_rawDesc)))
	})
	return file_download_proto_rawDescData
}

var file_download_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_download_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_download_proto_goTypes = []any{
	(Status)(0),             // 0: Status
	(*FileMeta)(nil),        // 1: FileMeta
	(*DownloadTask)(nil),    // 2: DownloadTask
	(*DownloadSummary)(nil), // 3: DownloadSummary
	(*FileChunk)(nil),       // 4: FileChunk
	(*DownloadStatus)(nil),  // 5: DownloadStatus
}
var file_download_proto_depIdxs = []int32{
	1, // 0: DownloadTask.meta:type_name -> FileMeta
	1, // 1: DownloadSummary.meta:type_name -> FileMeta
	1, // 2: FileChunk.meta:type_name -> FileMeta
	1, // 3: DownloadStatus.meta:type_name -> FileMeta
	2, // 4: DownloadService.PreDownload:input_type -> DownloadTask
	4, // 5: DownloadService.Download:input_type -> FileChunk
	3, // 6: DownloadService.PreDownload:output_type -> DownloadSummary
	5, // 7: DownloadService.Download:output_type -> DownloadStatus
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_download_proto_init() }
func file_download_proto_init() {
	if File_download_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_download_proto_rawDesc), len(file_download_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_download_proto_goTypes,
		DependencyIndexes: file_download_proto_depIdxs,
		EnumInfos:         file_download_proto_enumTypes,
		MessageInfos:      file_download_proto_msgTypes,
	}.Build()
	File_download_proto = out.File
	file_download_proto_goTypes = nil
	file_download_proto_depIdxs = nil
}
