// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileSelectionDialog() {
  return window['go']['main']['App']['OpenFileSelectionDialog']();
}

export function UploadFile(arg1) {
  return window['go']['main']['App']['UploadFile'](arg1);
}
