// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1:Array<string>):Promise<void>;

export function LinkGen(arg1:Array<string>):Promise<void>;

export function OpenFileSelectionDialog():Promise<string>;

export function UploadFile(arg1:Array<string>):Promise<void>;
